name: Build with node

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    environment:
      name: github-pages
      url: ${{steps.deploy.outputs.page_url}}
    steps:
    - uses: actions/checkout@v3
    - name: Install Python and rdflib
      run: sudo apt-get install -y python3 python3-rdflib
    - name: Set up node.js ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node-version}}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run check
    - name: Set up pages
      uses: actions/configure-pages@v3
    - name: Upload pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'public'
    - name: Deploy pages
      id: deployment
      uses: actions/deploy-pages@v2